### ISSUE TITLE
Running sensu-cli through a pipe is sometimes noisey

### ISSUE THREAD

**Issue by solarkennedy** [agent462/sensu-cli#26]
When I pipe sensu-cli through something that kills the sensu-cli proc mid-stream, it gets a broken-pipe exception:

```
$ sensu-cli client list -f json | grep -q something
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/pretty.rb:39:in `write': Broken pipe - <STDOUT> (Errno::EPIPE)
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/pretty.rb:39:in `puts'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/pretty.rb:39:in `puts'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/pretty.rb:39:in `json'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/base.rb:59:in `make_call'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/lib/sensu-cli/base.rb:7:in `setup'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-cli-0.6.1/bin/sensu-cli:6:in `<top (required)>'
    from /usr/bin/sensu-cli:23:in `load'
    from /usr/bin/sensu-cli:23:in `<main>'
```

But only if I have grep -q?

Can you try to repo this on a setup you have to confirm it is not just me?

**Comment by solarkennedy** [comment]
Heh, I though this might be fixed by STDOUT.sync = true, but it is not.

Keeping this issue closed and I won't think about it anymore because I can't reproduce it on lucid with sensu .13. It only seems to happen on our .12 clusters, which are being phased out.
